### ISSUE TITLE
improve nfs_mount role

### ISSUE THREAD

**Issue by A1ve5** [CSCfi/ansible-role-nfs_mount#2]
nfs_mount role isn't perfect, it seems to work but it can use some improvement
maybe use mount module

**Comment by jabl** [comment]
Indeed, with current Ansible this module generates a warning:

 [WARNING]: Consider using mount module rather than running mount

**Comment by martbhell** [comment]
PR for the improvement added in #3 

For FGCI before/after that is accepted/merged we could change to using the new nfs_mounts variable (poor name?) in examples/group_vars in fgci-ansible repo

**Comment by martbhell** [comment]
Let's update guides / etc after the role is available in fgci-ansible master. New issue about that in https://github.com/CSC-IT-Center-for-Science/fgci-ansible/issues/152
